#-----------------------------------------------

title:
  en: 'Portal'
  gr: 'Δικτυακή Πύλη'
subtitle:
  gr: "All tools in one place"

#-----------------------------------------------

sync: false
contact: false
search: false
cookies: false
footer: false
languages_toolbar: false
languages_sidebar: false
services: true
lockSidebar: false
menu:
  side: true
  top: false

language:
  default:
    key: 'en'
    value: 'English'
  extra:
    -
      key: 'gr'
      value: 'Ελληνικά'
      skipBuild: true

#-----------------------------------------------

toolbar:
  image: false
  icon: 'icons/agneta/logo'
  title: true

#-----------------------------------------------

recaptcha_key: ''
gmaps_key: ''
disqus_shortname: ''
google_analytics: ''
google_maps: ''

#-----------------------------------------------

authorization:
  - administrator

minify:
  html: true
  js: false


#-----------------------------------------------

scripts:
  - 'lib/socketcluster.min'
  - 'main/socket'
  - 'main/portal'
  - 'portal/main'
  - 'lib/angular-i18n/angular-locale_el-gr'
  - 'lib/bluebird.min'
