#-----------------------------------------------

theme:
  primary: 'blue'
  accent: 'blue-grey'

language:
  default:
    key: 'en'
    value: 'English'
  extra: false

services: true
scrollTop: true
sync: true

toolbar:
  icon: 'icons/agneta/logo'
  title: true

menu:
  top: false
  side: true

colors:
  primary: '#2196F3'
  accent: '#b4c3cf'
  primary-darker: '#0371C9'

#-----------------------------------------------

page:
  viewBase:
    local: 'private/page-local'
    default: 'private/page'

media:
  storageRoot: 'page'
  base: 'private/media'
  api:
    public: 'services/api/Media/'
    private: 'services/api/Media_Private/'
  partial:
    public: 'file'
    private: 'file-private'

#-----------------------------------------------

minify:
  html: true
  css: true
  js: true

#-----------------------------------------------

cookies: true
search: true
languages_toolbar: false
languages_sidebar: true
languages_footer: true

#-----------------------------------------------

scripts:
  - 'main'
  - 'lib/fuse.min'
  - 'lib/string.min'
  - 'lib/es6-promise.auto.min'

#-----------------------------------------------

angular_libs:
-
  js: 'lib/angular-aria.min'
-
  js: 'lib/angular-animate.min'
-
  dep: 'ngMessages'
  js: 'lib/angular-messages.min'
-
  dep: 'ngMaterial'
  js: 'lib/angular-material.min'
-
  dep: 'ngResource'
  js: 'lib/angular-resource.min'
-
  dep: 'oc.lazyLoad'
  js: 'lib/ocLazyLoad.min'
-
  dep: 'ngRoute'
  js: 'lib/angular-route.min'
-
  dep: 'ngSanitize'
  js: 'lib/angular-sanitize.min'
-
  dep: 'ngStorage'
  js: 'lib/ngStorage.min'
